name: publish-main

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: 
  contents: read
  packages: write 
  
jobs:
  build:
  
    name: publish-main
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
      id-token: write
      packages: write
      attestations: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    # Publish to GitHub Container Registry
    - name: Authenticate with GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Extract tags/labels
      id: meta-ghcr
      uses: docker/metadata-action@v5
      with:
        github-token: ${{ github.token }}
        images: ghcr.io/${{ github.repository }}
    
    - name: Publish to Github Container Registry
      id: push-ghcr
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta-ghcr.outputs.tags }}
        labels: ${{ steps.meta-ghcr.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ghcr.io/${{ github.repository }}
        subject-digest: ${{ steps.push-ghcr.outputs.digest }}
        push-to-registry: true
  